// <auto-generated />
using System;
using AppData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppData.Migrations
{
    [DbContext(typeof(AppDbcontext))]
    [Migration("20241117144834_update_lan2")]
    partial class update_lan2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AppData.Model.ChatLieu", b =>
                {
                    b.Property<Guid>("IdChatLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChatLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdChatLieu");

                    b.ToTable("chatLieus");

                    b.HasData(
                        new
                        {
                            IdChatLieu = new Guid("6462b9cc-3795-4154-b85c-ebae41f3bd57"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 17, 21, 48, 33, 799, DateTimeKind.Local).AddTicks(8404),
                            NgayTao = new DateTime(2024, 11, 17, 21, 48, 33, 799, DateTimeKind.Local).AddTicks(8418),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenChatLieu = "Vải Cotton"
                        },
                        new
                        {
                            IdChatLieu = new Guid("be47a0ac-a266-4c79-9d8a-75ab8ae47b36"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 17, 21, 48, 33, 799, DateTimeKind.Local).AddTicks(8429),
                            NgayTao = new DateTime(2024, 11, 17, 21, 48, 33, 799, DateTimeKind.Local).AddTicks(8429),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenChatLieu = "Da thật"
                        },
                        new
                        {
                            IdChatLieu = new Guid("caecb48b-9b72-4291-aef6-58e3906d99e2"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 17, 21, 48, 33, 799, DateTimeKind.Local).AddTicks(8431),
                            NgayTao = new DateTime(2024, 11, 17, 21, 48, 33, 799, DateTimeKind.Local).AddTicks(8431),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenChatLieu = "Vải Polyester"
                        });
                });

            modelBuilder.Entity("AppData.Model.ChucVu", b =>
                {
                    b.Property<Guid>("IdChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdChucVu");

                    b.ToTable("chuVu");
                });

            modelBuilder.Entity("AppData.Model.DanhMuc", b =>
                {
                    b.Property<Guid>("IdDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDanhMuc");

                    b.ToTable("danhMuc");

                    b.HasData(
                        new
                        {
                            IdDanhMuc = new Guid("5036e79d-d219-4645-9aae-7315aecf436c"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 17, 21, 48, 33, 800, DateTimeKind.Local).AddTicks(5136),
                            NgayTao = new DateTime(2024, 11, 17, 21, 48, 33, 800, DateTimeKind.Local).AddTicks(5131),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenDanhMuc = "Giày Thể Thao"
                        },
                        new
                        {
                            IdDanhMuc = new Guid("d0e348c6-9575-4feb-aef8-164df3edc263"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 17, 21, 48, 33, 800, DateTimeKind.Local).AddTicks(5140),
                            NgayTao = new DateTime(2024, 11, 17, 21, 48, 33, 800, DateTimeKind.Local).AddTicks(5139),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenDanhMuc = "Giày Da"
                        },
                        new
                        {
                            IdDanhMuc = new Guid("3643b547-07b4-4b56-8312-9788c213d0f7"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 17, 21, 48, 33, 800, DateTimeKind.Local).AddTicks(5142),
                            NgayTao = new DateTime(2024, 11, 17, 21, 48, 33, 800, DateTimeKind.Local).AddTicks(5141),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenDanhMuc = "Giày Cao Gót"
                        });
                });

            modelBuilder.Entity("AppData.Model.DeGiay", b =>
                {
                    b.Property<Guid>("IdDeGiay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDeGiay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDeGiay");

                    b.ToTable("deGiay");

                    b.HasData(
                        new
                        {
                            IdDeGiay = new Guid("808b3ebe-bd6f-4cef-af9e-454c3ffe03bf"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenDeGiay = "Đế cao su"
                        },
                        new
                        {
                            IdDeGiay = new Guid("423d6e16-7e46-4013-88e5-3f73db8df173"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenDeGiay = "Đế nhựa"
                        },
                        new
                        {
                            IdDeGiay = new Guid("dda1d026-ebd8-4915-b7f3-e240842eb086"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenDeGiay = "Đế vải"
                        });
                });

            modelBuilder.Entity("AppData.Model.DiaChi", b =>
                {
                    b.Property<Guid>("IdDiaChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DiaChiMacDinh")
                        .HasColumnType("bit");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("WardId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WardName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDiaChi");

                    b.HasIndex("IdKhachHang");

                    b.ToTable("diaChi");
                });

            modelBuilder.Entity("AppData.Model.District", b =>
                {
                    b.Property<int>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistrictId"), 1L, 1);

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("DistrictId");

                    b.ToTable("districts");
                });

            modelBuilder.Entity("AppData.Model.GioHang", b =>
                {
                    b.Property<Guid>("IdGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdGioHang");

                    b.HasIndex("IdKhachHang")
                        .IsUnique();

                    b.ToTable("gioHang");
                });

            modelBuilder.Entity("AppData.Model.GioHangChiTiet", b =>
                {
                    b.Property<Guid>("IdGioHangChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<Guid>("IdGioHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<double>("SoLuong")
                        .HasColumnType("float");

                    b.Property<double>("TongTien")
                        .HasColumnType("float");

                    b.HasKey("IdGioHangChiTiet");

                    b.HasIndex("IdGioHang");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.ToTable("gioHangChiTiets");
                });

            modelBuilder.Entity("AppData.Model.HinhAnh", b =>
                {
                    b.Property<Guid>("IdHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("DataHinhAnh")
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoaiFileHinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdHinhAnh");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.ToTable("hinhAnh");
                });

            modelBuilder.Entity("AppData.Model.HoaDon", b =>
                {
                    b.Property<Guid>("IdHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChiGiaoHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<string>("LoaiHoaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoaiNguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TienGiam")
                        .HasColumnType("float");

                    b.Property<double?>("TienShip")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<double>("TongTienDonHang")
                        .HasColumnType("float");

                    b.Property<double>("TongTienHoaDon")
                        .HasColumnType("float");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHoaDon");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdNhanVien");

                    b.ToTable("hoaDons");
                });

            modelBuilder.Entity("AppData.Model.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("IdHoaDonChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("KichHoat")
                        .HasColumnType("float");

                    b.Property<double>("SoLuong")
                        .HasColumnType("float");

                    b.Property<double>("TongTien")
                        .HasColumnType("float");

                    b.HasKey("IdHoaDonChiTiet");

                    b.HasIndex("IdHoaDon");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.ToTable("hoaDonChiTiets");
                });

            modelBuilder.Entity("AppData.Model.KhachHang", b =>
                {
                    b.Property<Guid>("IdKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdKhachHang");

                    b.ToTable("khachHangs");
                });

            modelBuilder.Entity("AppData.Model.KichCo", b =>
                {
                    b.Property<Guid>("IdKichCo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKichCo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKichCo");

                    b.ToTable("kichCos");

                    b.HasData(
                        new
                        {
                            IdKichCo = new Guid("4d4740f4-db6b-461c-b874-46aa42555a6f"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 17, 21, 48, 33, 805, DateTimeKind.Local).AddTicks(4701),
                            NgayTao = new DateTime(2024, 11, 17, 21, 48, 33, 805, DateTimeKind.Local).AddTicks(4715),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenKichCo = "Size 37"
                        },
                        new
                        {
                            IdKichCo = new Guid("71ce3af5-d60e-4047-8e85-91d793b00e18"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 17, 21, 48, 33, 805, DateTimeKind.Local).AddTicks(4718),
                            NgayTao = new DateTime(2024, 11, 17, 21, 48, 33, 805, DateTimeKind.Local).AddTicks(4718),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenKichCo = "Size 38"
                        },
                        new
                        {
                            IdKichCo = new Guid("71b9d9e3-29aa-4000-990e-42c0096db7fb"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 17, 21, 48, 33, 805, DateTimeKind.Local).AddTicks(4720),
                            NgayTao = new DateTime(2024, 11, 17, 21, 48, 33, 805, DateTimeKind.Local).AddTicks(4720),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenKichCo = "Size 39"
                        });
                });

            modelBuilder.Entity("AppData.Model.KieuDang", b =>
                {
                    b.Property<Guid>("IdKieuDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKieuDang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKieuDang");

                    b.ToTable("kieuDangs");

                    b.HasData(
                        new
                        {
                            IdKieuDang = new Guid("318574a9-ba42-44ca-83e5-f248c0a48f7d"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 17, 21, 48, 33, 805, DateTimeKind.Local).AddTicks(8438),
                            NgayTao = new DateTime(2024, 11, 17, 21, 48, 33, 805, DateTimeKind.Local).AddTicks(8432),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenKieuDang = "Thể Thao"
                        },
                        new
                        {
                            IdKieuDang = new Guid("7add19d8-490c-4ecf-b4f1-d920d5ad637d"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 17, 21, 48, 33, 805, DateTimeKind.Local).AddTicks(8440),
                            NgayTao = new DateTime(2024, 11, 17, 21, 48, 33, 805, DateTimeKind.Local).AddTicks(8440),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenKieuDang = "Cổ Điển"
                        },
                        new
                        {
                            IdKieuDang = new Guid("30a92d7d-5125-40ac-ba8e-904cf488cba9"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 17, 21, 48, 33, 805, DateTimeKind.Local).AddTicks(8442),
                            NgayTao = new DateTime(2024, 11, 17, 21, 48, 33, 805, DateTimeKind.Local).AddTicks(8442),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenKieuDang = "Hiện Đại"
                        });
                });

            modelBuilder.Entity("AppData.Model.LichSuHoaDon", b =>
                {
                    b.Property<Guid>("IdLichSuHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiThaoTac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThaoTac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLichSuHoaDon");

                    b.HasIndex("IdHoaDon");

                    b.HasIndex("IdNhanVien");

                    b.ToTable("lichSuHoaDons");
                });

            modelBuilder.Entity("AppData.Model.LichSuSuDungVoucher", b =>
                {
                    b.Property<Guid>("IdVoucher")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdLichSuVoucher")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdOrder")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgaySuDungVoucher")
                        .HasColumnType("datetime2");

                    b.HasKey("IdVoucher", "IdKhachHang");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdVoucher", "IdKhachHang", "IdOrder")
                        .IsUnique();

                    b.ToTable("LichSuSuDungVouchers");
                });

            modelBuilder.Entity("AppData.Model.MauSac", b =>
                {
                    b.Property<Guid>("IdMauSac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenMauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMauSac");

                    b.ToTable("mauSacs");

                    b.HasData(
                        new
                        {
                            IdMauSac = new Guid("46a1faf8-a01b-4505-aaa7-7b48cbfa7f32"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 17, 21, 48, 33, 806, DateTimeKind.Local).AddTicks(9877),
                            NgayTao = new DateTime(2024, 11, 17, 21, 48, 33, 806, DateTimeKind.Local).AddTicks(9881),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenMauSac = "Red"
                        },
                        new
                        {
                            IdMauSac = new Guid("33430c16-0d88-479d-8dbe-ba4b9eb69fee"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 17, 21, 48, 33, 806, DateTimeKind.Local).AddTicks(9883),
                            NgayTao = new DateTime(2024, 11, 17, 21, 48, 33, 806, DateTimeKind.Local).AddTicks(9883),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenMauSac = "Green"
                        },
                        new
                        {
                            IdMauSac = new Guid("898789d1-1b0f-4da8-bea5-fdbf589e94a9"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 17, 21, 48, 33, 806, DateTimeKind.Local).AddTicks(9891),
                            NgayTao = new DateTime(2024, 11, 17, 21, 48, 33, 806, DateTimeKind.Local).AddTicks(9892),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenMauSac = "Blue"
                        });
                });

            modelBuilder.Entity("AppData.Model.NhanVien", b =>
                {
                    b.Property<Guid>("IdNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnhNhanVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdchucVu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("KichHoat")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhanVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdNhanVien");

                    b.HasIndex("IdchucVu");

                    b.ToTable("nhanViens");
                });

            modelBuilder.Entity("AppData.Model.Promotion", b =>
                {
                    b.Property<Guid>("IdPromotion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhanTramGiam")
                        .HasColumnType("int");

                    b.Property<string>("TenPromotion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdPromotion");

                    b.ToTable("promotions");
                });

            modelBuilder.Entity("AppData.Model.PromotionSanPhamChiTiet", b =>
                {
                    b.Property<Guid>("IdPromotion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdPromotion", "IdSanPhamChiTiet");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.ToTable("PromotionSanPhamChiTiet");
                });

            modelBuilder.Entity("AppData.Model.Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvinceId"), 1L, 1);

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinceId");

                    b.ToTable("provinces");
                });

            modelBuilder.Entity("AppData.Model.SanPham", b =>
                {
                    b.Property<Guid>("IdSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdChatLieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDanhMuc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDeGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdKieuDang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdThuongHieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Sale")
                        .HasColumnType("float");

                    b.Property<string>("TenSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSanPham");

                    b.HasIndex("IdChatLieu");

                    b.HasIndex("IdDanhMuc");

                    b.HasIndex("IdDeGiay");

                    b.HasIndex("IdKieuDang");

                    b.HasIndex("IdThuongHieu");

                    b.ToTable("sanPhams");
                });

            modelBuilder.Entity("AppData.Model.SanPhamChiTiet", b =>
                {
                    b.Property<Guid>("IdSanPhamChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoHienThi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Gia")
                        .HasColumnType("float");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SoLuong")
                        .HasColumnType("float");

                    b.Property<string>("XuatXu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSanPhamChiTiet");

                    b.HasIndex("IdSanPham");

                    b.ToTable("sanPhamChiTiets");
                });

            modelBuilder.Entity("AppData.Model.SanPhamChiTietKichCo", b =>
                {
                    b.Property<Guid>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdKichCo")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdSanPhamChiTiet", "IdKichCo");

                    b.HasIndex("IdKichCo");

                    b.ToTable("sanPhamChiTietKichCos");
                });

            modelBuilder.Entity("AppData.Model.SanPhamChiTietMauSac", b =>
                {
                    b.Property<Guid>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMauSac")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdSanPhamChiTiet", "IdMauSac");

                    b.HasIndex("IdMauSac");

                    b.ToTable("sanPhamChiTietMausacs");
                });

            modelBuilder.Entity("AppData.Model.ThuongHieu", b =>
                {
                    b.Property<Guid>("IdThuongHieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThuongHieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdThuongHieu");

                    b.ToTable("thuongHieus");

                    b.HasData(
                        new
                        {
                            IdThuongHieu = new Guid("fd2cf426-561f-4f55-90c6-cee0308a0208"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 17, 21, 48, 33, 812, DateTimeKind.Local).AddTicks(2660),
                            NgayTao = new DateTime(2024, 11, 17, 21, 48, 33, 812, DateTimeKind.Local).AddTicks(2646),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenThuongHieu = "Nike"
                        },
                        new
                        {
                            IdThuongHieu = new Guid("4f69e642-755a-457d-aace-20185eec66ca"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 17, 21, 48, 33, 812, DateTimeKind.Local).AddTicks(2662),
                            NgayTao = new DateTime(2024, 11, 17, 21, 48, 33, 812, DateTimeKind.Local).AddTicks(2662),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenThuongHieu = "Adidas"
                        },
                        new
                        {
                            IdThuongHieu = new Guid("bf4acc84-8cf3-41d3-aa88-f240a78aed45"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 17, 21, 48, 33, 812, DateTimeKind.Local).AddTicks(2665),
                            NgayTao = new DateTime(2024, 11, 17, 21, 48, 33, 812, DateTimeKind.Local).AddTicks(2664),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenThuongHieu = "Puma"
                        });
                });

            modelBuilder.Entity("AppData.Model.Voucher", b =>
                {
                    b.Property<Guid>("VoucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("GiaTriDonHangToiThieu")
                        .HasColumnType("int");

                    b.Property<int>("GiaTriGiam")
                        .HasColumnType("int");

                    b.Property<int>("LoaiGiamGia")
                        .HasColumnType("int");

                    b.Property<string>("MaVoucher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaVoucher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuongVoucherConLai")
                        .HasColumnType("int");

                    b.Property<int?>("SoTienToiDa")
                        .HasColumnType("int");

                    b.Property<int>("TongSoLuongVoucher")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("VoucherId");

                    b.ToTable("vouchers");
                });

            modelBuilder.Entity("AppData.Model.Ward", b =>
                {
                    b.Property<string>("WardId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("WardName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WardId");

                    b.ToTable("wards");
                });

            modelBuilder.Entity("AppData.Model.DiaChi", b =>
                {
                    b.HasOne("AppData.Model.KhachHang", "khachHang")
                        .WithMany("DiaChis")
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("khachHang");
                });

            modelBuilder.Entity("AppData.Model.GioHang", b =>
                {
                    b.HasOne("AppData.Model.KhachHang", "KhachHang")
                        .WithOne("GioHang")
                        .HasForeignKey("AppData.Model.GioHang", "IdKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("AppData.Model.GioHangChiTiet", b =>
                {
                    b.HasOne("AppData.Model.GioHang", "GioHang")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("IdGioHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("IdSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GioHang");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("AppData.Model.HinhAnh", b =>
                {
                    b.HasOne("AppData.Model.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("HinhAnhs")
                        .HasForeignKey("IdSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("AppData.Model.HoaDon", b =>
                {
                    b.HasOne("AppData.Model.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdKhachHang");

                    b.HasOne("AppData.Model.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdNhanVien");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("AppData.Model.HoaDonChiTiet", b =>
                {
                    b.HasOne("AppData.Model.HoaDon", "HoaDon")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("AppData.Model.LichSuHoaDon", b =>
                {
                    b.HasOne("AppData.Model.HoaDon", "HoaDon")
                        .WithMany("LichSuHoaDons")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.NhanVien", "NhanVien")
                        .WithMany("LichSuHoaDons")
                        .HasForeignKey("IdNhanVien")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HoaDon");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("AppData.Model.LichSuSuDungVoucher", b =>
                {
                    b.HasOne("AppData.Model.KhachHang", "KhachHang")
                        .WithMany("LichSuSuDungVouchers")
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppData.Model.Voucher", "Voucher")
                        .WithMany("LichSuSuDungVouchers")
                        .HasForeignKey("IdVoucher")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("AppData.Model.NhanVien", b =>
                {
                    b.HasOne("AppData.Model.ChucVu", "chucVu")
                        .WithMany("nhanViens")
                        .HasForeignKey("IdchucVu");

                    b.Navigation("chucVu");
                });

            modelBuilder.Entity("AppData.Model.PromotionSanPhamChiTiet", b =>
                {
                    b.HasOne("AppData.Model.Promotion", "Promotion")
                        .WithMany("PromotionSanPhamChiTiets")
                        .HasForeignKey("IdPromotion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("PromotionSanPhamChiTiets")
                        .HasForeignKey("IdSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promotion");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("AppData.Model.SanPham", b =>
                {
                    b.HasOne("AppData.Model.ChatLieu", "ChatLieu")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdChatLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.DanhMuc", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.DeGiay", "DeGiay")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdDeGiay")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.KieuDang", "KieuDang")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdKieuDang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.ThuongHieu", "ThuongHieu")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdThuongHieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatLieu");

                    b.Navigation("DanhMuc");

                    b.Navigation("DeGiay");

                    b.Navigation("KieuDang");

                    b.Navigation("ThuongHieu");
                });

            modelBuilder.Entity("AppData.Model.SanPhamChiTiet", b =>
                {
                    b.HasOne("AppData.Model.SanPham", "SanPham")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("AppData.Model.SanPhamChiTietKichCo", b =>
                {
                    b.HasOne("AppData.Model.KichCo", "KichCo")
                        .WithMany("SanPhamChiTietKichCos")
                        .HasForeignKey("IdKichCo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("SanPhamChiTietKichCos")
                        .HasForeignKey("IdSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KichCo");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("AppData.Model.SanPhamChiTietMauSac", b =>
                {
                    b.HasOne("AppData.Model.MauSac", "MauSac")
                        .WithMany("SanPhamChiTietMauSacs")
                        .HasForeignKey("IdMauSac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("SanPhamChiTietMauSacs")
                        .HasForeignKey("IdSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MauSac");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("AppData.Model.ChatLieu", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("AppData.Model.ChucVu", b =>
                {
                    b.Navigation("nhanViens");
                });

            modelBuilder.Entity("AppData.Model.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("AppData.Model.DeGiay", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("AppData.Model.GioHang", b =>
                {
                    b.Navigation("GioHangChiTiets");
                });

            modelBuilder.Entity("AppData.Model.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiets");

                    b.Navigation("LichSuHoaDons");
                });

            modelBuilder.Entity("AppData.Model.KhachHang", b =>
                {
                    b.Navigation("DiaChis");

                    b.Navigation("GioHang");

                    b.Navigation("HoaDons");

                    b.Navigation("LichSuSuDungVouchers");
                });

            modelBuilder.Entity("AppData.Model.KichCo", b =>
                {
                    b.Navigation("SanPhamChiTietKichCos");
                });

            modelBuilder.Entity("AppData.Model.KieuDang", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("AppData.Model.MauSac", b =>
                {
                    b.Navigation("SanPhamChiTietMauSacs");
                });

            modelBuilder.Entity("AppData.Model.NhanVien", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("LichSuHoaDons");
                });

            modelBuilder.Entity("AppData.Model.Promotion", b =>
                {
                    b.Navigation("PromotionSanPhamChiTiets");
                });

            modelBuilder.Entity("AppData.Model.SanPham", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("AppData.Model.SanPhamChiTiet", b =>
                {
                    b.Navigation("GioHangChiTiets");

                    b.Navigation("HinhAnhs");

                    b.Navigation("HoaDonChiTiets");

                    b.Navigation("PromotionSanPhamChiTiets");

                    b.Navigation("SanPhamChiTietKichCos");

                    b.Navigation("SanPhamChiTietMauSacs");
                });

            modelBuilder.Entity("AppData.Model.ThuongHieu", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("AppData.Model.Voucher", b =>
                {
                    b.Navigation("LichSuSuDungVouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
