// <auto-generated />
using System;
using AppData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppData.Migrations
{
    [DbContext(typeof(AppDbcontext))]
    [Migration("20241022030918_duan")]
    partial class duan
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AppData.Model.ChatLieu", b =>
                {
                    b.Property<Guid>("IdChatLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChatLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdChatLieu");

                    b.ToTable("chatLieus");

                    b.HasData(
                        new
                        {
                            IdChatLieu = new Guid("b3542bd8-af83-4d21-a0ce-7d37ace8a8a8"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 10, 22, 10, 9, 18, 566, DateTimeKind.Local).AddTicks(2040),
                            NgayTao = new DateTime(2024, 10, 22, 10, 9, 18, 566, DateTimeKind.Local).AddTicks(2049),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenChatLieu = "Vải Cotton"
                        },
                        new
                        {
                            IdChatLieu = new Guid("0f073ed3-7024-4fce-abcb-b5ac2f647f9c"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 10, 22, 10, 9, 18, 566, DateTimeKind.Local).AddTicks(2052),
                            NgayTao = new DateTime(2024, 10, 22, 10, 9, 18, 566, DateTimeKind.Local).AddTicks(2052),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenChatLieu = "Da thật"
                        },
                        new
                        {
                            IdChatLieu = new Guid("3433a0b0-e8ef-4451-8719-b8c91de93283"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 10, 22, 10, 9, 18, 566, DateTimeKind.Local).AddTicks(2054),
                            NgayTao = new DateTime(2024, 10, 22, 10, 9, 18, 566, DateTimeKind.Local).AddTicks(2054),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenChatLieu = "Vải Polyester"
                        });
                });

            modelBuilder.Entity("AppData.Model.ChucVu", b =>
                {
                    b.Property<Guid>("IdChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdChucVu");

                    b.ToTable("chuVu");
                });

            modelBuilder.Entity("AppData.Model.DanhMuc", b =>
                {
                    b.Property<Guid>("IdDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDanhMuc");

                    b.ToTable("danhMuc");

                    b.HasData(
                        new
                        {
                            IdDanhMuc = new Guid("4a00d76a-1d4b-41e9-923d-f4ca6eb327cd"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 10, 22, 10, 9, 18, 566, DateTimeKind.Local).AddTicks(7019),
                            NgayTao = new DateTime(2024, 10, 22, 10, 9, 18, 566, DateTimeKind.Local).AddTicks(7016),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenDanhMuc = "Giày Thể Thao"
                        },
                        new
                        {
                            IdDanhMuc = new Guid("e8f69a47-b994-4851-b436-5c6935dca4de"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 10, 22, 10, 9, 18, 566, DateTimeKind.Local).AddTicks(7022),
                            NgayTao = new DateTime(2024, 10, 22, 10, 9, 18, 566, DateTimeKind.Local).AddTicks(7022),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenDanhMuc = "Giày Da"
                        },
                        new
                        {
                            IdDanhMuc = new Guid("4303a0c2-f5b0-4709-b8f0-fc6b6145f803"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 10, 22, 10, 9, 18, 566, DateTimeKind.Local).AddTicks(7025),
                            NgayTao = new DateTime(2024, 10, 22, 10, 9, 18, 566, DateTimeKind.Local).AddTicks(7024),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenDanhMuc = "Giày Cao Gót"
                        });
                });

            modelBuilder.Entity("AppData.Model.DeGiay", b =>
                {
                    b.Property<Guid>("IdDeGiay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDeGiay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDeGiay");

                    b.ToTable("deGiay");

                    b.HasData(
                        new
                        {
                            IdDeGiay = new Guid("c620d7ff-d430-49a0-bf1a-9b90394a5b91"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenDeGiay = "Đế cao su"
                        },
                        new
                        {
                            IdDeGiay = new Guid("b1d6648f-345c-49d5-a777-fb39562f6ce2"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenDeGiay = "Đế nhựa"
                        },
                        new
                        {
                            IdDeGiay = new Guid("9b8c128f-6725-4750-a140-11cef1a79b44"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenDeGiay = "Đế vải"
                        });
                });

            modelBuilder.Entity("AppData.Model.DiaChi", b =>
                {
                    b.Property<Guid>("IdDiaChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChiMacDinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdDiaChi");

                    b.HasIndex("IdKhachHang");

                    b.ToTable("diaChi");
                });

            modelBuilder.Entity("AppData.Model.GiaoDich", b =>
                {
                    b.Property<Guid>("IdGiaoDich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTrangThai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdGiaoDich");

                    b.HasIndex("IdHoaDon");

                    b.HasIndex("IdTrangThai");

                    b.ToTable("giaoDiches");
                });

            modelBuilder.Entity("AppData.Model.GioHang", b =>
                {
                    b.Property<Guid>("IdGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdGioHang");

                    b.ToTable("gioHang");
                });

            modelBuilder.Entity("AppData.Model.GioHangChiTiet", b =>
                {
                    b.Property<Guid>("IdGioHangChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<Guid>("IdGioHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<double>("SoLuong")
                        .HasColumnType("float");

                    b.Property<double>("TongTien")
                        .HasColumnType("float");

                    b.HasKey("IdGioHangChiTiet");

                    b.HasIndex("IdGioHang");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.ToTable("gioHangChiTiets");
                });

            modelBuilder.Entity("AppData.Model.HinhAnh", b =>
                {
                    b.Property<Guid?>("IdHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("DataHinhAnh")
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid?>("IdMauSac")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoaiFileHinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdHinhAnh");

                    b.HasIndex("IdMauSac");

                    b.ToTable("hinhAnh");
                });

            modelBuilder.Entity("AppData.Model.HoaDon", b =>
                {
                    b.Property<Guid>("IdHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChiGiaoHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTrangThai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<string>("LoaiHoaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoaiNguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TienGiam")
                        .HasColumnType("float");

                    b.Property<double>("TienShip")
                        .HasColumnType("float");

                    b.Property<double>("TongTienDonHang")
                        .HasColumnType("float");

                    b.Property<double>("TongTienHoaDon")
                        .HasColumnType("float");

                    b.HasKey("IdHoaDon");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdNhanVien");

                    b.HasIndex("IdTrangThai");

                    b.ToTable("hoaDons");
                });

            modelBuilder.Entity("AppData.Model.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("IdHoaDonChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("KichHoat")
                        .HasColumnType("float");

                    b.Property<double>("SoLuong")
                        .HasColumnType("float");

                    b.Property<double>("TongTien")
                        .HasColumnType("float");

                    b.HasKey("IdHoaDonChiTiet");

                    b.HasIndex("IdHoaDon");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.ToTable("hoaDonChiTiets");
                });

            modelBuilder.Entity("AppData.Model.KhachHang", b =>
                {
                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KichHoat")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdKhachHang");

                    b.ToTable("khachHangs");
                });

            modelBuilder.Entity("AppData.Model.KichCo", b =>
                {
                    b.Property<Guid>("IdKichCo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKichCo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKichCo");

                    b.ToTable("kichCos");

                    b.HasData(
                        new
                        {
                            IdKichCo = new Guid("8208649f-4c33-4fa0-87f5-d596b284062e"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 10, 22, 10, 9, 18, 571, DateTimeKind.Local).AddTicks(7662),
                            NgayTao = new DateTime(2024, 10, 22, 10, 9, 18, 571, DateTimeKind.Local).AddTicks(7673),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenKichCo = "Small"
                        },
                        new
                        {
                            IdKichCo = new Guid("d0779b99-1c31-41a3-b8f3-9338caadf761"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 10, 22, 10, 9, 18, 571, DateTimeKind.Local).AddTicks(7675),
                            NgayTao = new DateTime(2024, 10, 22, 10, 9, 18, 571, DateTimeKind.Local).AddTicks(7676),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenKichCo = "Medium"
                        },
                        new
                        {
                            IdKichCo = new Guid("518da839-58a3-40e0-b193-e551e402e160"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 10, 22, 10, 9, 18, 571, DateTimeKind.Local).AddTicks(7693),
                            NgayTao = new DateTime(2024, 10, 22, 10, 9, 18, 571, DateTimeKind.Local).AddTicks(7694),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenKichCo = "Large"
                        });
                });

            modelBuilder.Entity("AppData.Model.KieuDang", b =>
                {
                    b.Property<Guid>("IdKieuDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKieuDang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKieuDang");

                    b.ToTable("kieuDangs");

                    b.HasData(
                        new
                        {
                            IdKieuDang = new Guid("a611e18e-1eb1-44f1-96a0-726e69024078"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 10, 22, 10, 9, 18, 572, DateTimeKind.Local).AddTicks(481),
                            NgayTao = new DateTime(2024, 10, 22, 10, 9, 18, 572, DateTimeKind.Local).AddTicks(476),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenKieuDang = "Thể Thao"
                        },
                        new
                        {
                            IdKieuDang = new Guid("e6133b42-beef-45c5-a17f-4e22c14e5aac"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 10, 22, 10, 9, 18, 572, DateTimeKind.Local).AddTicks(483),
                            NgayTao = new DateTime(2024, 10, 22, 10, 9, 18, 572, DateTimeKind.Local).AddTicks(483),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenKieuDang = "Cổ Điển"
                        },
                        new
                        {
                            IdKieuDang = new Guid("e67f369d-23e4-4bd8-a1e3-546b896a4e4f"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 10, 22, 10, 9, 18, 572, DateTimeKind.Local).AddTicks(485),
                            NgayTao = new DateTime(2024, 10, 22, 10, 9, 18, 572, DateTimeKind.Local).AddTicks(485),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenKieuDang = "Hiện Đại"
                        });
                });

            modelBuilder.Entity("AppData.Model.LichSuHoaDon", b =>
                {
                    b.Property<Guid>("IdLichSuHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiThaoTac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThaoTac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLichSuHoaDon");

                    b.HasIndex("IdHoaDon");

                    b.ToTable("lichSuHoaDons");
                });

            modelBuilder.Entity("AppData.Model.MauSac", b =>
                {
                    b.Property<Guid?>("IdMauSac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenMauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMauSac");

                    b.ToTable("mauSacs");

                    b.HasData(
                        new
                        {
                            IdMauSac = new Guid("5179547b-9dbb-4c67-8f97-ca8423e5bc29"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 10, 22, 10, 9, 18, 572, DateTimeKind.Local).AddTicks(5520),
                            NgayTao = new DateTime(2024, 10, 22, 10, 9, 18, 572, DateTimeKind.Local).AddTicks(5527),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenMauSac = "Red"
                        },
                        new
                        {
                            IdMauSac = new Guid("7a957344-1eab-4a4d-90e9-abbd430d50f7"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 10, 22, 10, 9, 18, 572, DateTimeKind.Local).AddTicks(5529),
                            NgayTao = new DateTime(2024, 10, 22, 10, 9, 18, 572, DateTimeKind.Local).AddTicks(5529),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenMauSac = "Green"
                        },
                        new
                        {
                            IdMauSac = new Guid("c16d53ee-d97b-4920-98d7-b95c9598e3ed"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 10, 22, 10, 9, 18, 572, DateTimeKind.Local).AddTicks(5531),
                            NgayTao = new DateTime(2024, 10, 22, 10, 9, 18, 572, DateTimeKind.Local).AddTicks(5532),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenMauSac = "Blue"
                        });
                });

            modelBuilder.Entity("AppData.Model.NhanVien", b =>
                {
                    b.Property<Guid>("IdNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnhNhanVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdchucVu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("KichHoat")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenNhanVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdNhanVien");

                    b.HasIndex("IdchucVu");

                    b.ToTable("nhanViens");
                });

            modelBuilder.Entity("AppData.Model.Promotion", b =>
                {
                    b.Property<Guid>("IdPromotion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhanTramGiam")
                        .HasColumnType("int");

                    b.Property<string>("TenPromotion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdPromotion");

                    b.ToTable("promotions");
                });

            modelBuilder.Entity("AppData.Model.PromotionSanPhamChiTiet", b =>
                {
                    b.Property<Guid>("IdPromotion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdPromotion", "IdSanPhamChiTiet");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.ToTable("PromotionSanPhamChiTiet");
                });

            modelBuilder.Entity("AppData.Model.SanPham", b =>
                {
                    b.Property<Guid>("IdSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdChatLieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdDanhMuc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdDeGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdKieuDang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdThuongHieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Sale")
                        .HasColumnType("float");

                    b.Property<string>("TenSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSanPham");

                    b.HasIndex("IdChatLieu");

                    b.HasIndex("IdDanhMuc");

                    b.HasIndex("IdDeGiay");

                    b.HasIndex("IdKieuDang");

                    b.HasIndex("IdThuongHieu");

                    b.ToTable("sanPhams");
                });

            modelBuilder.Entity("AppData.Model.SanPhamChiTiet", b =>
                {
                    b.Property<Guid>("IdSanPhamChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoHienThi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Gia")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("SoLuong")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<string>("XuatXu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSanPhamChiTiet");

                    b.HasIndex("IdSanPham");

                    b.ToTable("sanPhamChiTiets");
                });

            modelBuilder.Entity("AppData.Model.SanPhamChiTietKichCo", b =>
                {
                    b.Property<Guid>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdKichCo")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdSanPhamChiTiet", "IdKichCo");

                    b.HasIndex("IdKichCo");

                    b.ToTable("sanPhamChiTietKichCos");
                });

            modelBuilder.Entity("AppData.Model.SanPhamChiTietMauSac", b =>
                {
                    b.Property<Guid>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMauSac")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdSanPhamChiTiet", "IdMauSac");

                    b.HasIndex("IdMauSac");

                    b.ToTable("sanPhamChiTietMausacs");
                });

            modelBuilder.Entity("AppData.Model.ThuongHieu", b =>
                {
                    b.Property<Guid>("IdThuongHieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThuongHieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdThuongHieu");

                    b.ToTable("thuongHieus");

                    b.HasData(
                        new
                        {
                            IdThuongHieu = new Guid("a4e4bc52-7d73-4c77-a1ee-89906a48dc32"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 10, 22, 10, 9, 18, 576, DateTimeKind.Local).AddTicks(2337),
                            NgayTao = new DateTime(2024, 10, 22, 10, 9, 18, 576, DateTimeKind.Local).AddTicks(2331),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenThuongHieu = "Nike"
                        },
                        new
                        {
                            IdThuongHieu = new Guid("cb89c56c-dfcf-4347-a1d8-b5f684c58470"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 10, 22, 10, 9, 18, 576, DateTimeKind.Local).AddTicks(2351),
                            NgayTao = new DateTime(2024, 10, 22, 10, 9, 18, 576, DateTimeKind.Local).AddTicks(2350),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenThuongHieu = "Adidas"
                        },
                        new
                        {
                            IdThuongHieu = new Guid("307cbd07-8d5c-4ecc-b3a7-6032bb8cdc57"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 10, 22, 10, 9, 18, 576, DateTimeKind.Local).AddTicks(2353),
                            NgayTao = new DateTime(2024, 10, 22, 10, 9, 18, 576, DateTimeKind.Local).AddTicks(2352),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenThuongHieu = "Puma"
                        });
                });

            modelBuilder.Entity("AppData.Model.TrangThai", b =>
                {
                    b.Property<Guid>("IdTrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTrangThai");

                    b.ToTable("trangThais");
                });

            modelBuilder.Entity("AppData.Model.DiaChi", b =>
                {
                    b.HasOne("AppData.Model.KhachHang", "khachHang")
                        .WithMany("DiaChis")
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("khachHang");
                });

            modelBuilder.Entity("AppData.Model.GiaoDich", b =>
                {
                    b.HasOne("AppData.Model.HoaDon", "HoaDon")
                        .WithMany("GiaoDichs")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AppData.Model.TrangThai", "TrangThai")
                        .WithMany("GiaoDich")
                        .HasForeignKey("IdTrangThai")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("TrangThai");
                });

            modelBuilder.Entity("AppData.Model.GioHangChiTiet", b =>
                {
                    b.HasOne("AppData.Model.GioHang", "GioHang")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("IdGioHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("IdSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GioHang");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("AppData.Model.HinhAnh", b =>
                {
                    b.HasOne("AppData.Model.MauSac", "MauSac")
                        .WithMany("HinhAnhs")
                        .HasForeignKey("IdMauSac");

                    b.Navigation("MauSac");
                });

            modelBuilder.Entity("AppData.Model.HoaDon", b =>
                {
                    b.HasOne("AppData.Model.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.TrangThai", "TrangThai")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdTrangThai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");

                    b.Navigation("TrangThai");
                });

            modelBuilder.Entity("AppData.Model.HoaDonChiTiet", b =>
                {
                    b.HasOne("AppData.Model.HoaDon", "HoaDon")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("AppData.Model.KhachHang", b =>
                {
                    b.HasOne("AppData.Model.GioHang", "GioHang")
                        .WithOne("KhachHang")
                        .HasForeignKey("AppData.Model.KhachHang", "IdKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GioHang");
                });

            modelBuilder.Entity("AppData.Model.LichSuHoaDon", b =>
                {
                    b.HasOne("AppData.Model.HoaDon", "HoaDon")
                        .WithMany("LichSuHoaDons")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("AppData.Model.NhanVien", b =>
                {
                    b.HasOne("AppData.Model.ChucVu", "chucVu")
                        .WithMany("nhanViens")
                        .HasForeignKey("IdchucVu");

                    b.Navigation("chucVu");
                });

            modelBuilder.Entity("AppData.Model.PromotionSanPhamChiTiet", b =>
                {
                    b.HasOne("AppData.Model.Promotion", "Promotion")
                        .WithMany("PromotionSanPhamChiTiets")
                        .HasForeignKey("IdPromotion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("PromotionSanPhamChiTiets")
                        .HasForeignKey("IdSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promotion");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("AppData.Model.SanPham", b =>
                {
                    b.HasOne("AppData.Model.ChatLieu", "ChatLieu")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdChatLieu");

                    b.HasOne("AppData.Model.DanhMuc", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdDanhMuc");

                    b.HasOne("AppData.Model.DeGiay", "DeGiay")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdDeGiay");

                    b.HasOne("AppData.Model.KieuDang", "KieuDang")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdKieuDang");

                    b.HasOne("AppData.Model.ThuongHieu", "ThuongHieu")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdThuongHieu");

                    b.Navigation("ChatLieu");

                    b.Navigation("DanhMuc");

                    b.Navigation("DeGiay");

                    b.Navigation("KieuDang");

                    b.Navigation("ThuongHieu");
                });

            modelBuilder.Entity("AppData.Model.SanPhamChiTiet", b =>
                {
                    b.HasOne("AppData.Model.SanPham", "SanPham")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdSanPham");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("AppData.Model.SanPhamChiTietKichCo", b =>
                {
                    b.HasOne("AppData.Model.KichCo", "KichCo")
                        .WithMany("SanPhamChiTietKichCos")
                        .HasForeignKey("IdKichCo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("SanPhamChiTietKichCos")
                        .HasForeignKey("IdSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KichCo");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("AppData.Model.SanPhamChiTietMauSac", b =>
                {
                    b.HasOne("AppData.Model.MauSac", "MauSac")
                        .WithMany("SanPhamChiTietMauSacs")
                        .HasForeignKey("IdMauSac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("SanPhamChiTietMauSacs")
                        .HasForeignKey("IdSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MauSac");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("AppData.Model.ChatLieu", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("AppData.Model.ChucVu", b =>
                {
                    b.Navigation("nhanViens");
                });

            modelBuilder.Entity("AppData.Model.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("AppData.Model.DeGiay", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("AppData.Model.GioHang", b =>
                {
                    b.Navigation("GioHangChiTiets");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("AppData.Model.HoaDon", b =>
                {
                    b.Navigation("GiaoDichs");

                    b.Navigation("HoaDonChiTiets");

                    b.Navigation("LichSuHoaDons");
                });

            modelBuilder.Entity("AppData.Model.KhachHang", b =>
                {
                    b.Navigation("DiaChis");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("AppData.Model.KichCo", b =>
                {
                    b.Navigation("SanPhamChiTietKichCos");
                });

            modelBuilder.Entity("AppData.Model.KieuDang", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("AppData.Model.MauSac", b =>
                {
                    b.Navigation("HinhAnhs");

                    b.Navigation("SanPhamChiTietMauSacs");
                });

            modelBuilder.Entity("AppData.Model.NhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("AppData.Model.Promotion", b =>
                {
                    b.Navigation("PromotionSanPhamChiTiets");
                });

            modelBuilder.Entity("AppData.Model.SanPham", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("AppData.Model.SanPhamChiTiet", b =>
                {
                    b.Navigation("GioHangChiTiets");

                    b.Navigation("HoaDonChiTiets");

                    b.Navigation("PromotionSanPhamChiTiets");

                    b.Navigation("SanPhamChiTietKichCos");

                    b.Navigation("SanPhamChiTietMauSacs");
                });

            modelBuilder.Entity("AppData.Model.ThuongHieu", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("AppData.Model.TrangThai", b =>
                {
                    b.Navigation("GiaoDich");

                    b.Navigation("HoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
