// <auto-generated />
using System;
using AppData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppData.Migrations
{
    [DbContext(typeof(AppDbcontext))]
    partial class AppDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AppData.Model.ChatLieu", b =>
                {
                    b.Property<Guid>("IdChatLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChatLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdChatLieu");

                    b.ToTable("chatLieus");

                    b.HasData(
                        new
                        {
                            IdChatLieu = new Guid("8f7496b7-6891-4296-80dd-4b4ed8256689"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 13, 9, 9, 24, 644, DateTimeKind.Local).AddTicks(5485),
                            NgayTao = new DateTime(2024, 11, 13, 9, 9, 24, 644, DateTimeKind.Local).AddTicks(5495),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenChatLieu = "Vải Cotton"
                        },
                        new
                        {
                            IdChatLieu = new Guid("611a3b71-4431-45f4-8313-57b0afbe71f6"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 13, 9, 9, 24, 644, DateTimeKind.Local).AddTicks(5497),
                            NgayTao = new DateTime(2024, 11, 13, 9, 9, 24, 644, DateTimeKind.Local).AddTicks(5497),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenChatLieu = "Da thật"
                        },
                        new
                        {
                            IdChatLieu = new Guid("2ba0d5f4-9597-428e-aaba-4c8046046746"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 13, 9, 9, 24, 644, DateTimeKind.Local).AddTicks(5499),
                            NgayTao = new DateTime(2024, 11, 13, 9, 9, 24, 644, DateTimeKind.Local).AddTicks(5499),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenChatLieu = "Vải Polyester"
                        });
                });

            modelBuilder.Entity("AppData.Model.ChucVu", b =>
                {
                    b.Property<Guid>("IdChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdChucVu");

                    b.ToTable("chuVu");
                });

            modelBuilder.Entity("AppData.Model.DanhMuc", b =>
                {
                    b.Property<Guid>("IdDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDanhMuc");

                    b.ToTable("danhMuc");

                    b.HasData(
                        new
                        {
                            IdDanhMuc = new Guid("e1c3a5b3-bf5a-425c-9127-c4ebb1ed007d"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 13, 9, 9, 24, 645, DateTimeKind.Local).AddTicks(646),
                            NgayTao = new DateTime(2024, 11, 13, 9, 9, 24, 645, DateTimeKind.Local).AddTicks(638),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenDanhMuc = "Giày Thể Thao"
                        },
                        new
                        {
                            IdDanhMuc = new Guid("1414bbac-7970-423e-90bf-a42273f4e11b"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 13, 9, 9, 24, 645, DateTimeKind.Local).AddTicks(660),
                            NgayTao = new DateTime(2024, 11, 13, 9, 9, 24, 645, DateTimeKind.Local).AddTicks(659),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenDanhMuc = "Giày Da"
                        },
                        new
                        {
                            IdDanhMuc = new Guid("e04f8cb9-c36a-46eb-9fbe-c0e3fa5bdbde"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 13, 9, 9, 24, 645, DateTimeKind.Local).AddTicks(662),
                            NgayTao = new DateTime(2024, 11, 13, 9, 9, 24, 645, DateTimeKind.Local).AddTicks(661),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenDanhMuc = "Giày Cao Gót"
                        });
                });

            modelBuilder.Entity("AppData.Model.DeGiay", b =>
                {
                    b.Property<Guid>("IdDeGiay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDeGiay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDeGiay");

                    b.ToTable("deGiay");

                    b.HasData(
                        new
                        {
                            IdDeGiay = new Guid("aa922a2d-8fa9-4dd2-8578-2b3bc87c5ee3"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenDeGiay = "Đế cao su"
                        },
                        new
                        {
                            IdDeGiay = new Guid("4ffb0139-3f54-433f-b1c6-ab7c0ba3cc4d"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenDeGiay = "Đế nhựa"
                        },
                        new
                        {
                            IdDeGiay = new Guid("db704cf8-b6e5-4b04-8124-879a488d49ce"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenDeGiay = "Đế vải"
                        });
                });

            modelBuilder.Entity("AppData.Model.DiaChi", b =>
                {
                    b.Property<Guid>("IdDiaChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DiaChiMacDinh")
                        .HasColumnType("bit");

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdDiaChi");

                    b.HasIndex("IdKhachHang");

                    b.ToTable("diaChi");
                });

            modelBuilder.Entity("AppData.Model.GiaoDich", b =>
                {
                    b.Property<Guid>("IdGiaoDich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTrangThai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdGiaoDich");

                    b.HasIndex("IdHoaDon");

                    b.HasIndex("IdNhanVien");

                    b.HasIndex("IdTrangThai");

                    b.ToTable("giaoDiches");
                });

            modelBuilder.Entity("AppData.Model.GioHang", b =>
                {
                    b.Property<Guid>("IdGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdGioHang");

                    b.HasIndex("IdKhachHang")
                        .IsUnique();

                    b.ToTable("gioHang");
                });

            modelBuilder.Entity("AppData.Model.GioHangChiTiet", b =>
                {
                    b.Property<Guid>("IdGioHangChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("DonGia")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<Guid>("IdGioHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<double?>("SoLuong")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<double?>("TongTien")
                        .IsRequired()
                        .HasColumnType("float");

                    b.HasKey("IdGioHangChiTiet");

                    b.HasIndex("IdGioHang");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.ToTable("gioHangChiTiets");
                });

            modelBuilder.Entity("AppData.Model.HinhAnh", b =>
                {
                    b.Property<Guid>("IdHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("DataHinhAnh")
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoaiFileHinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdHinhAnh");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.ToTable("hinhAnh");
                });

            modelBuilder.Entity("AppData.Model.HoaDon", b =>
                {
                    b.Property<Guid>("IdHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChiGiaoHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTrangThai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<string>("LoaiHoaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoaiNguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TienGiam")
                        .HasColumnType("float");

                    b.Property<double>("TienShip")
                        .HasColumnType("float");

                    b.Property<double>("TongTienDonHang")
                        .HasColumnType("float");

                    b.Property<double>("TongTienHoaDon")
                        .HasColumnType("float");

                    b.HasKey("IdHoaDon");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdNhanVien");

                    b.HasIndex("IdTrangThai");

                    b.ToTable("hoaDons");
                });

            modelBuilder.Entity("AppData.Model.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("IdHoaDonChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("KichHoat")
                        .HasColumnType("float");

                    b.Property<double>("SoLuong")
                        .HasColumnType("float");

                    b.Property<double>("TongTien")
                        .HasColumnType("float");

                    b.HasKey("IdHoaDonChiTiet");

                    b.HasIndex("IdHoaDon");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.ToTable("hoaDonChiTiets");
                });

            modelBuilder.Entity("AppData.Model.KhachHang", b =>
                {
                    b.Property<Guid>("IdKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdKhachHang");

                    b.ToTable("khachHangs");
                });

            modelBuilder.Entity("AppData.Model.KichCo", b =>
                {
                    b.Property<Guid>("IdKichCo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKichCo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKichCo");

                    b.ToTable("kichCos");

                    b.HasData(
                        new
                        {
                            IdKichCo = new Guid("9128213d-4704-4df9-b77f-7bf46af3f577"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 13, 9, 9, 24, 650, DateTimeKind.Local).AddTicks(2029),
                            NgayTao = new DateTime(2024, 11, 13, 9, 9, 24, 650, DateTimeKind.Local).AddTicks(2039),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenKichCo = "Small"
                        },
                        new
                        {
                            IdKichCo = new Guid("027135a0-e89b-4321-a237-04540d3c09a4"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 13, 9, 9, 24, 650, DateTimeKind.Local).AddTicks(2042),
                            NgayTao = new DateTime(2024, 11, 13, 9, 9, 24, 650, DateTimeKind.Local).AddTicks(2042),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenKichCo = "Medium"
                        },
                        new
                        {
                            IdKichCo = new Guid("900c6898-13b6-4a43-8e61-aa3079ef90b3"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 13, 9, 9, 24, 650, DateTimeKind.Local).AddTicks(2044),
                            NgayTao = new DateTime(2024, 11, 13, 9, 9, 24, 650, DateTimeKind.Local).AddTicks(2044),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenKichCo = "Large"
                        });
                });

            modelBuilder.Entity("AppData.Model.KieuDang", b =>
                {
                    b.Property<Guid>("IdKieuDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKieuDang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKieuDang");

                    b.ToTable("kieuDangs");

                    b.HasData(
                        new
                        {
                            IdKieuDang = new Guid("dd76640f-bc57-4a93-a14f-73a51ff85501"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 13, 9, 9, 24, 650, DateTimeKind.Local).AddTicks(5811),
                            NgayTao = new DateTime(2024, 11, 13, 9, 9, 24, 650, DateTimeKind.Local).AddTicks(5806),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenKieuDang = "Thể Thao"
                        },
                        new
                        {
                            IdKieuDang = new Guid("88d706c3-7efc-45f2-84f3-1d613e08034f"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 13, 9, 9, 24, 650, DateTimeKind.Local).AddTicks(5814),
                            NgayTao = new DateTime(2024, 11, 13, 9, 9, 24, 650, DateTimeKind.Local).AddTicks(5813),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenKieuDang = "Cổ Điển"
                        },
                        new
                        {
                            IdKieuDang = new Guid("5aaf39fc-4346-4126-984f-5309c336e579"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 13, 9, 9, 24, 650, DateTimeKind.Local).AddTicks(5817),
                            NgayTao = new DateTime(2024, 11, 13, 9, 9, 24, 650, DateTimeKind.Local).AddTicks(5817),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenKieuDang = "Hiện Đại"
                        });
                });

            modelBuilder.Entity("AppData.Model.LichSuHoaDon", b =>
                {
                    b.Property<Guid>("IdLichSuHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiThaoTac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThaoTac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLichSuHoaDon");

                    b.HasIndex("IdHoaDon");

                    b.ToTable("lichSuHoaDons");
                });

            modelBuilder.Entity("AppData.Model.LichSuSuDungVoucher", b =>
                {
                    b.Property<Guid>("IdVoucher")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdLichSuVoucher")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdOrder")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgaySuDungVoucher")
                        .HasColumnType("datetime2");

                    b.HasKey("IdVoucher", "IdKhachHang");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdVoucher", "IdKhachHang", "IdOrder")
                        .IsUnique();

                    b.ToTable("LichSuSuDungVouchers");
                });

            modelBuilder.Entity("AppData.Model.MauSac", b =>
                {
                    b.Property<Guid>("IdMauSac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenMauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMauSac");

                    b.ToTable("mauSacs");

                    b.HasData(
                        new
                        {
                            IdMauSac = new Guid("36d1179f-e6ca-41e7-ac43-3f6b73bb9f0a"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 13, 9, 9, 24, 651, DateTimeKind.Local).AddTicks(5413),
                            NgayTao = new DateTime(2024, 11, 13, 9, 9, 24, 651, DateTimeKind.Local).AddTicks(5426),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenMauSac = "Red"
                        },
                        new
                        {
                            IdMauSac = new Guid("02b09518-f335-4124-928e-3da73ab0ca1c"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 13, 9, 9, 24, 651, DateTimeKind.Local).AddTicks(5428),
                            NgayTao = new DateTime(2024, 11, 13, 9, 9, 24, 651, DateTimeKind.Local).AddTicks(5429),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenMauSac = "Green"
                        },
                        new
                        {
                            IdMauSac = new Guid("21e20540-f585-42a1-b389-b4e5d56c92d1"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 13, 9, 9, 24, 651, DateTimeKind.Local).AddTicks(5430),
                            NgayTao = new DateTime(2024, 11, 13, 9, 9, 24, 651, DateTimeKind.Local).AddTicks(5431),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenMauSac = "Blue"
                        });
                });

            modelBuilder.Entity("AppData.Model.NhanVien", b =>
                {
                    b.Property<Guid>("IdNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnhNhanVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdchucVu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("KichHoat")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhanVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdNhanVien");

                    b.HasIndex("IdchucVu");

                    b.ToTable("nhanViens");
                });

            modelBuilder.Entity("AppData.Model.Promotion", b =>
                {
                    b.Property<Guid>("IdPromotion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhanTramGiam")
                        .HasColumnType("int");

                    b.Property<string>("TenPromotion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdPromotion");

                    b.ToTable("promotions");
                });

            modelBuilder.Entity("AppData.Model.PromotionSanPhamChiTiet", b =>
                {
                    b.Property<Guid>("IdPromotion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdPromotion", "IdSanPhamChiTiet");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.ToTable("PromotionSanPhamChiTiet");
                });

            modelBuilder.Entity("AppData.Model.SanPham", b =>
                {
                    b.Property<Guid>("IdSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdChatLieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDanhMuc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDeGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdKieuDang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdThuongHieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Sale")
                        .HasColumnType("float");

                    b.Property<string>("TenSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSanPham");

                    b.HasIndex("IdChatLieu");

                    b.HasIndex("IdDanhMuc");

                    b.HasIndex("IdDeGiay");

                    b.HasIndex("IdKieuDang");

                    b.HasIndex("IdThuongHieu");

                    b.ToTable("sanPhams");
                });

            modelBuilder.Entity("AppData.Model.SanPhamChiTiet", b =>
                {
                    b.Property<Guid>("IdSanPhamChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoHienThi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Gia")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("SoLuong")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<string>("XuatXu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSanPhamChiTiet");

                    b.HasIndex("IdSanPham");

                    b.ToTable("sanPhamChiTiets");
                });

            modelBuilder.Entity("AppData.Model.SanPhamChiTietKichCo", b =>
                {
                    b.Property<Guid>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdKichCo")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdSanPhamChiTiet", "IdKichCo");

                    b.HasIndex("IdKichCo");

                    b.ToTable("sanPhamChiTietKichCos");
                });

            modelBuilder.Entity("AppData.Model.SanPhamChiTietMauSac", b =>
                {
                    b.Property<Guid>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMauSac")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdSanPhamChiTiet", "IdMauSac");

                    b.HasIndex("IdMauSac");

                    b.ToTable("sanPhamChiTietMausacs");
                });

            modelBuilder.Entity("AppData.Model.ThuongHieu", b =>
                {
                    b.Property<Guid>("IdThuongHieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThuongHieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdThuongHieu");

                    b.ToTable("thuongHieus");

                    b.HasData(
                        new
                        {
                            IdThuongHieu = new Guid("08ce4174-5943-480e-8bfa-8a97782ab402"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 13, 9, 9, 24, 657, DateTimeKind.Local).AddTicks(3051),
                            NgayTao = new DateTime(2024, 11, 13, 9, 9, 24, 657, DateTimeKind.Local).AddTicks(3041),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenThuongHieu = "Nike"
                        },
                        new
                        {
                            IdThuongHieu = new Guid("d2247264-c4c4-400d-a174-a6278b434ce3"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 13, 9, 9, 24, 657, DateTimeKind.Local).AddTicks(3054),
                            NgayTao = new DateTime(2024, 11, 13, 9, 9, 24, 657, DateTimeKind.Local).AddTicks(3054),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenThuongHieu = "Adidas"
                        },
                        new
                        {
                            IdThuongHieu = new Guid("55514bb5-fa8f-4bc8-a28c-722a8e1943d3"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 13, 9, 9, 24, 657, DateTimeKind.Local).AddTicks(3070),
                            NgayTao = new DateTime(2024, 11, 13, 9, 9, 24, 657, DateTimeKind.Local).AddTicks(3069),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenThuongHieu = "Puma"
                        });
                });

            modelBuilder.Entity("AppData.Model.TrangThai", b =>
                {
                    b.Property<Guid>("IdTrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTrangThai");

                    b.ToTable("trangThais");
                });

            modelBuilder.Entity("AppData.Model.Voucher", b =>
                {
                    b.Property<Guid>("VoucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("GiaTriDonHangToiThieu")
                        .HasColumnType("int");

                    b.Property<int>("GiaTriGiam")
                        .HasColumnType("int");

                    b.Property<int>("LoaiGiamGia")
                        .HasColumnType("int");

                    b.Property<string>("MaVoucher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaVoucher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuongVoucherConLai")
                        .HasColumnType("int");

                    b.Property<int?>("SoTienToiDa")
                        .HasColumnType("int");

                    b.Property<int>("TongSoLuongVoucher")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("VoucherId");

                    b.ToTable("vouchers");
                });

            modelBuilder.Entity("AppData.Model.DiaChi", b =>
                {
                    b.HasOne("AppData.Model.KhachHang", "khachHang")
                        .WithMany("DiaChis")
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("khachHang");
                });

            modelBuilder.Entity("AppData.Model.GiaoDich", b =>
                {
                    b.HasOne("AppData.Model.HoaDon", "HoaDon")
                        .WithMany("GiaoDichs")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AppData.Model.NhanVien", "NhanVien")
                        .WithMany("GiaoDiches")
                        .HasForeignKey("IdNhanVien")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AppData.Model.TrangThai", "TrangThai")
                        .WithMany("GiaoDich")
                        .HasForeignKey("IdTrangThai")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("NhanVien");

                    b.Navigation("TrangThai");
                });

            modelBuilder.Entity("AppData.Model.GioHang", b =>
                {
                    b.HasOne("AppData.Model.KhachHang", "KhachHang")
                        .WithOne("GioHang")
                        .HasForeignKey("AppData.Model.GioHang", "IdKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("AppData.Model.GioHangChiTiet", b =>
                {
                    b.HasOne("AppData.Model.GioHang", "GioHang")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("IdGioHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("IdSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GioHang");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("AppData.Model.HinhAnh", b =>
                {
                    b.HasOne("AppData.Model.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("HinhAnhs")
                        .HasForeignKey("IdSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("AppData.Model.HoaDon", b =>
                {
                    b.HasOne("AppData.Model.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.TrangThai", "TrangThai")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdTrangThai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");

                    b.Navigation("TrangThai");
                });

            modelBuilder.Entity("AppData.Model.HoaDonChiTiet", b =>
                {
                    b.HasOne("AppData.Model.HoaDon", "HoaDon")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("AppData.Model.LichSuHoaDon", b =>
                {
                    b.HasOne("AppData.Model.HoaDon", "HoaDon")
                        .WithMany("LichSuHoaDons")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("AppData.Model.LichSuSuDungVoucher", b =>
                {
                    b.HasOne("AppData.Model.KhachHang", "KhachHang")
                        .WithMany("LichSuSuDungVouchers")
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppData.Model.Voucher", "Voucher")
                        .WithMany("LichSuSuDungVouchers")
                        .HasForeignKey("IdVoucher")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("AppData.Model.NhanVien", b =>
                {
                    b.HasOne("AppData.Model.ChucVu", "chucVu")
                        .WithMany("nhanViens")
                        .HasForeignKey("IdchucVu");

                    b.Navigation("chucVu");
                });

            modelBuilder.Entity("AppData.Model.PromotionSanPhamChiTiet", b =>
                {
                    b.HasOne("AppData.Model.Promotion", "Promotion")
                        .WithMany("PromotionSanPhamChiTiets")
                        .HasForeignKey("IdPromotion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("PromotionSanPhamChiTiets")
                        .HasForeignKey("IdSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promotion");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("AppData.Model.SanPham", b =>
                {
                    b.HasOne("AppData.Model.ChatLieu", "ChatLieu")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdChatLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.DanhMuc", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.DeGiay", "DeGiay")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdDeGiay")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.KieuDang", "KieuDang")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdKieuDang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.ThuongHieu", "ThuongHieu")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdThuongHieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatLieu");

                    b.Navigation("DanhMuc");

                    b.Navigation("DeGiay");

                    b.Navigation("KieuDang");

                    b.Navigation("ThuongHieu");
                });

            modelBuilder.Entity("AppData.Model.SanPhamChiTiet", b =>
                {
                    b.HasOne("AppData.Model.SanPham", "SanPham")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("AppData.Model.SanPhamChiTietKichCo", b =>
                {
                    b.HasOne("AppData.Model.KichCo", "KichCo")
                        .WithMany("SanPhamChiTietKichCos")
                        .HasForeignKey("IdKichCo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("SanPhamChiTietKichCos")
                        .HasForeignKey("IdSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KichCo");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("AppData.Model.SanPhamChiTietMauSac", b =>
                {
                    b.HasOne("AppData.Model.MauSac", "MauSac")
                        .WithMany("SanPhamChiTietMauSacs")
                        .HasForeignKey("IdMauSac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("SanPhamChiTietMauSacs")
                        .HasForeignKey("IdSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MauSac");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("AppData.Model.ChatLieu", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("AppData.Model.ChucVu", b =>
                {
                    b.Navigation("nhanViens");
                });

            modelBuilder.Entity("AppData.Model.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("AppData.Model.DeGiay", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("AppData.Model.GioHang", b =>
                {
                    b.Navigation("GioHangChiTiets");
                });

            modelBuilder.Entity("AppData.Model.HoaDon", b =>
                {
                    b.Navigation("GiaoDichs");

                    b.Navigation("HoaDonChiTiets");

                    b.Navigation("LichSuHoaDons");
                });

            modelBuilder.Entity("AppData.Model.KhachHang", b =>
                {
                    b.Navigation("DiaChis");

                    b.Navigation("GioHang");

                    b.Navigation("HoaDons");

                    b.Navigation("LichSuSuDungVouchers");
                });

            modelBuilder.Entity("AppData.Model.KichCo", b =>
                {
                    b.Navigation("SanPhamChiTietKichCos");
                });

            modelBuilder.Entity("AppData.Model.KieuDang", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("AppData.Model.MauSac", b =>
                {
                    b.Navigation("SanPhamChiTietMauSacs");
                });

            modelBuilder.Entity("AppData.Model.NhanVien", b =>
                {
                    b.Navigation("GiaoDiches");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("AppData.Model.Promotion", b =>
                {
                    b.Navigation("PromotionSanPhamChiTiets");
                });

            modelBuilder.Entity("AppData.Model.SanPham", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("AppData.Model.SanPhamChiTiet", b =>
                {
                    b.Navigation("GioHangChiTiets");

                    b.Navigation("HinhAnhs");

                    b.Navigation("HoaDonChiTiets");

                    b.Navigation("PromotionSanPhamChiTiets");

                    b.Navigation("SanPhamChiTietKichCos");

                    b.Navigation("SanPhamChiTietMauSacs");
                });

            modelBuilder.Entity("AppData.Model.ThuongHieu", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("AppData.Model.TrangThai", b =>
                {
                    b.Navigation("GiaoDich");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("AppData.Model.Voucher", b =>
                {
                    b.Navigation("LichSuSuDungVouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
