// <auto-generated />
using System;
using AppData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppData.Migrations
{
    [DbContext(typeof(AppDbcontext))]
    partial class AppDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AppData.Model.ChatLieu", b =>
                {
                    b.Property<Guid>("IdChatLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChatLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdChatLieu");

                    b.ToTable("chatLieus");

                    b.HasData(
                        new
                        {
                            IdChatLieu = new Guid("0e0d56fd-d795-43b4-ae93-b74bde9b0c8f"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 15, 20, 18, 50, 342, DateTimeKind.Local).AddTicks(3035),
                            NgayTao = new DateTime(2024, 11, 15, 20, 18, 50, 342, DateTimeKind.Local).AddTicks(3046),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenChatLieu = "Vải Cotton"
                        },
                        new
                        {
                            IdChatLieu = new Guid("3a6e5f20-84f4-4c19-b3eb-54f43da7a51f"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 15, 20, 18, 50, 342, DateTimeKind.Local).AddTicks(3049),
                            NgayTao = new DateTime(2024, 11, 15, 20, 18, 50, 342, DateTimeKind.Local).AddTicks(3049),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenChatLieu = "Da thật"
                        },
                        new
                        {
                            IdChatLieu = new Guid("e6a06295-9abf-4a54-add9-941d746281f4"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 15, 20, 18, 50, 342, DateTimeKind.Local).AddTicks(3051),
                            NgayTao = new DateTime(2024, 11, 15, 20, 18, 50, 342, DateTimeKind.Local).AddTicks(3051),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenChatLieu = "Vải Polyester"
                        });
                });

            modelBuilder.Entity("AppData.Model.ChucVu", b =>
                {
                    b.Property<Guid>("IdChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdChucVu");

                    b.ToTable("chuVu");
                });

            modelBuilder.Entity("AppData.Model.DanhMuc", b =>
                {
                    b.Property<Guid>("IdDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDanhMuc");

                    b.ToTable("danhMuc");

                    b.HasData(
                        new
                        {
                            IdDanhMuc = new Guid("c99642da-ea7d-4492-80d5-3dbe52a88931"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 15, 20, 18, 50, 342, DateTimeKind.Local).AddTicks(8982),
                            NgayTao = new DateTime(2024, 11, 15, 20, 18, 50, 342, DateTimeKind.Local).AddTicks(8978),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenDanhMuc = "Giày Thể Thao"
                        },
                        new
                        {
                            IdDanhMuc = new Guid("39d5a2e0-fd00-4adb-a2b0-5c735f1833d7"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 15, 20, 18, 50, 342, DateTimeKind.Local).AddTicks(8985),
                            NgayTao = new DateTime(2024, 11, 15, 20, 18, 50, 342, DateTimeKind.Local).AddTicks(8985),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenDanhMuc = "Giày Da"
                        },
                        new
                        {
                            IdDanhMuc = new Guid("94eaf87a-64cd-47a3-9309-22696eb61242"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 15, 20, 18, 50, 342, DateTimeKind.Local).AddTicks(8987),
                            NgayTao = new DateTime(2024, 11, 15, 20, 18, 50, 342, DateTimeKind.Local).AddTicks(8987),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenDanhMuc = "Giày Cao Gót"
                        });
                });

            modelBuilder.Entity("AppData.Model.DeGiay", b =>
                {
                    b.Property<Guid>("IdDeGiay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDeGiay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDeGiay");

                    b.ToTable("deGiay");

                    b.HasData(
                        new
                        {
                            IdDeGiay = new Guid("b6391b4f-083d-4f0f-a041-b8bee6f9c8de"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenDeGiay = "Đế cao su"
                        },
                        new
                        {
                            IdDeGiay = new Guid("79862a20-ddbf-42bf-bb43-e16d8534f35e"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenDeGiay = "Đế nhựa"
                        },
                        new
                        {
                            IdDeGiay = new Guid("d888f8dd-4aef-42fc-9613-facfb32edc28"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenDeGiay = "Đế vải"
                        });
                });

            modelBuilder.Entity("AppData.Model.DiaChi", b =>
                {
                    b.Property<Guid>("IdDiaChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DiaChiMacDinh")
                        .HasColumnType("bit");

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdDiaChi");

                    b.HasIndex("IdKhachHang");

                    b.ToTable("diaChi");
                });

            modelBuilder.Entity("AppData.Model.GioHang", b =>
                {
                    b.Property<Guid>("IdGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdGioHang");

                    b.HasIndex("IdKhachHang")
                        .IsUnique();

                    b.ToTable("gioHang");
                });

            modelBuilder.Entity("AppData.Model.GioHangChiTiet", b =>
                {
                    b.Property<Guid>("IdGioHangChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<Guid>("IdGioHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<double>("SoLuong")
                        .HasColumnType("float");

                    b.Property<double>("TongTien")
                        .HasColumnType("float");

                    b.HasKey("IdGioHangChiTiet");

                    b.HasIndex("IdGioHang");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.ToTable("gioHangChiTiets");
                });

            modelBuilder.Entity("AppData.Model.HinhAnh", b =>
                {
                    b.Property<Guid>("IdHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("DataHinhAnh")
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid?>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoaiFileHinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdHinhAnh");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.ToTable("hinhAnh");
                });

            modelBuilder.Entity("AppData.Model.HoaDon", b =>
                {
                    b.Property<Guid>("IdHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChiGiaoHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<string>("LoaiHoaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoaiNguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TienGiam")
                        .HasColumnType("float");

                    b.Property<double?>("TienShip")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<double>("TongTienDonHang")
                        .HasColumnType("float");

                    b.Property<double>("TongTienHoaDon")
                        .HasColumnType("float");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHoaDon");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdNhanVien");

                    b.ToTable("hoaDons");
                });

            modelBuilder.Entity("AppData.Model.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("IdHoaDonChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("KichHoat")
                        .HasColumnType("float");

                    b.Property<double>("SoLuong")
                        .HasColumnType("float");

                    b.Property<double>("TongTien")
                        .HasColumnType("float");

                    b.HasKey("IdHoaDonChiTiet");

                    b.HasIndex("IdHoaDon");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.ToTable("hoaDonChiTiets");
                });

            modelBuilder.Entity("AppData.Model.KhachHang", b =>
                {
                    b.Property<Guid>("IdKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdKhachHang");

                    b.ToTable("khachHangs");
                });

            modelBuilder.Entity("AppData.Model.KichCo", b =>
                {
                    b.Property<Guid>("IdKichCo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKichCo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKichCo");

                    b.ToTable("kichCos");

                    b.HasData(
                        new
                        {
                            IdKichCo = new Guid("aedbaf81-e8e4-459a-8826-f8d41f523535"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 15, 20, 18, 50, 347, DateTimeKind.Local).AddTicks(2234),
                            NgayTao = new DateTime(2024, 11, 15, 20, 18, 50, 347, DateTimeKind.Local).AddTicks(2238),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenKichCo = "Size 37"
                        },
                        new
                        {
                            IdKichCo = new Guid("f542e97f-d0af-403c-aee6-24d5359f617f"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 15, 20, 18, 50, 347, DateTimeKind.Local).AddTicks(2242),
                            NgayTao = new DateTime(2024, 11, 15, 20, 18, 50, 347, DateTimeKind.Local).AddTicks(2242),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenKichCo = "Size 38"
                        },
                        new
                        {
                            IdKichCo = new Guid("2e903dd9-bff6-41de-b302-0b516e8503f3"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 15, 20, 18, 50, 347, DateTimeKind.Local).AddTicks(2251),
                            NgayTao = new DateTime(2024, 11, 15, 20, 18, 50, 347, DateTimeKind.Local).AddTicks(2252),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenKichCo = "Size 39"
                        });
                });

            modelBuilder.Entity("AppData.Model.KieuDang", b =>
                {
                    b.Property<Guid>("IdKieuDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKieuDang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKieuDang");

                    b.ToTable("kieuDangs");

                    b.HasData(
                        new
                        {
                            IdKieuDang = new Guid("61350678-2e7f-490b-a049-347c48437106"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 15, 20, 18, 50, 347, DateTimeKind.Local).AddTicks(5689),
                            NgayTao = new DateTime(2024, 11, 15, 20, 18, 50, 347, DateTimeKind.Local).AddTicks(5687),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenKieuDang = "Thể Thao"
                        },
                        new
                        {
                            IdKieuDang = new Guid("f96b791e-1697-4777-bf30-110860fff8dc"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 15, 20, 18, 50, 347, DateTimeKind.Local).AddTicks(5692),
                            NgayTao = new DateTime(2024, 11, 15, 20, 18, 50, 347, DateTimeKind.Local).AddTicks(5692),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenKieuDang = "Cổ Điển"
                        },
                        new
                        {
                            IdKieuDang = new Guid("047cf0fb-9c1d-4b40-9ae7-38ab7ff3995f"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 15, 20, 18, 50, 347, DateTimeKind.Local).AddTicks(5695),
                            NgayTao = new DateTime(2024, 11, 15, 20, 18, 50, 347, DateTimeKind.Local).AddTicks(5694),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenKieuDang = "Hiện Đại"
                        });
                });

            modelBuilder.Entity("AppData.Model.LichSuHoaDon", b =>
                {
                    b.Property<Guid>("IdLichSuHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiThaoTac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThaoTac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLichSuHoaDon");

                    b.HasIndex("IdHoaDon");

                    b.HasIndex("IdNhanVien");

                    b.ToTable("lichSuHoaDons");
                });

            modelBuilder.Entity("AppData.Model.LichSuSuDungVoucher", b =>
                {
                    b.Property<Guid>("IdVoucher")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdLichSuVoucher")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdOrder")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgaySuDungVoucher")
                        .HasColumnType("datetime2");

                    b.HasKey("IdVoucher", "IdKhachHang");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdVoucher", "IdKhachHang", "IdOrder")
                        .IsUnique();

                    b.ToTable("LichSuSuDungVouchers");
                });

            modelBuilder.Entity("AppData.Model.MauSac", b =>
                {
                    b.Property<Guid>("IdMauSac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenMauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMauSac");

                    b.ToTable("mauSacs");

                    b.HasData(
                        new
                        {
                            IdMauSac = new Guid("badc0b7b-3034-40ee-b362-1a500985f26f"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 15, 20, 18, 50, 348, DateTimeKind.Local).AddTicks(6036),
                            NgayTao = new DateTime(2024, 11, 15, 20, 18, 50, 348, DateTimeKind.Local).AddTicks(6041),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenMauSac = "Red"
                        },
                        new
                        {
                            IdMauSac = new Guid("28550113-02ac-4d9d-a081-4fc6f62c7b69"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 15, 20, 18, 50, 348, DateTimeKind.Local).AddTicks(6044),
                            NgayTao = new DateTime(2024, 11, 15, 20, 18, 50, 348, DateTimeKind.Local).AddTicks(6044),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenMauSac = "Green"
                        },
                        new
                        {
                            IdMauSac = new Guid("a43891a8-71b1-4105-bdce-fdbdb1c0845a"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 15, 20, 18, 50, 348, DateTimeKind.Local).AddTicks(6046),
                            NgayTao = new DateTime(2024, 11, 15, 20, 18, 50, 348, DateTimeKind.Local).AddTicks(6046),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenMauSac = "Blue"
                        });
                });

            modelBuilder.Entity("AppData.Model.NhanVien", b =>
                {
                    b.Property<Guid>("IdNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnhNhanVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdchucVu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("KichHoat")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhanVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdNhanVien");

                    b.HasIndex("IdchucVu");

                    b.ToTable("nhanViens");
                });

            modelBuilder.Entity("AppData.Model.Promotion", b =>
                {
                    b.Property<Guid>("IdPromotion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhanTramGiam")
                        .HasColumnType("int");

                    b.Property<string>("TenPromotion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdPromotion");

                    b.ToTable("promotions");
                });

            modelBuilder.Entity("AppData.Model.PromotionSanPhamChiTiet", b =>
                {
                    b.Property<Guid>("IdPromotion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdPromotion", "IdSanPhamChiTiet");

                    b.HasIndex("IdSanPhamChiTiet");

                    b.ToTable("PromotionSanPhamChiTiet");
                });

            modelBuilder.Entity("AppData.Model.SanPham", b =>
                {
                    b.Property<Guid>("IdSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdChatLieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDanhMuc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDeGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdKieuDang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdThuongHieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Sale")
                        .HasColumnType("float");

                    b.Property<string>("TenSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSanPham");

                    b.HasIndex("IdChatLieu");

                    b.HasIndex("IdDanhMuc");

                    b.HasIndex("IdDeGiay");

                    b.HasIndex("IdKieuDang");

                    b.HasIndex("IdThuongHieu");

                    b.ToTable("sanPhams");
                });

            modelBuilder.Entity("AppData.Model.SanPhamChiTiet", b =>
                {
                    b.Property<Guid>("IdSanPhamChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoHienThi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Gia")
                        .HasColumnType("float");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SoLuong")
                        .HasColumnType("float");

                    b.Property<string>("XuatXu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSanPhamChiTiet");

                    b.HasIndex("IdSanPham");

                    b.ToTable("sanPhamChiTiets");
                });

            modelBuilder.Entity("AppData.Model.SanPhamChiTietKichCo", b =>
                {
                    b.Property<Guid>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdKichCo")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdSanPhamChiTiet", "IdKichCo");

                    b.HasIndex("IdKichCo");

                    b.ToTable("sanPhamChiTietKichCos");
                });

            modelBuilder.Entity("AppData.Model.SanPhamChiTietMauSac", b =>
                {
                    b.Property<Guid>("IdSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMauSac")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdSanPhamChiTiet", "IdMauSac");

                    b.HasIndex("IdMauSac");

                    b.ToTable("sanPhamChiTietMausacs");
                });

            modelBuilder.Entity("AppData.Model.ThuongHieu", b =>
                {
                    b.Property<Guid>("IdThuongHieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KichHoat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThuongHieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdThuongHieu");

                    b.ToTable("thuongHieus");

                    b.HasData(
                        new
                        {
                            IdThuongHieu = new Guid("405cdfea-e66f-4a01-91e1-e1be9a78f548"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 15, 20, 18, 50, 355, DateTimeKind.Local).AddTicks(2163),
                            NgayTao = new DateTime(2024, 11, 15, 20, 18, 50, 355, DateTimeKind.Local).AddTicks(2157),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenThuongHieu = "Nike"
                        },
                        new
                        {
                            IdThuongHieu = new Guid("3213c51a-c9cd-4ee6-967e-4882ab300210"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 15, 20, 18, 50, 355, DateTimeKind.Local).AddTicks(2174),
                            NgayTao = new DateTime(2024, 11, 15, 20, 18, 50, 355, DateTimeKind.Local).AddTicks(2173),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenThuongHieu = "Adidas"
                        },
                        new
                        {
                            IdThuongHieu = new Guid("a0840577-4c63-49ed-87bd-6c261e6797d1"),
                            KichHoat = 1,
                            NgayCapNhat = new DateTime(2024, 11, 15, 20, 18, 50, 355, DateTimeKind.Local).AddTicks(2178),
                            NgayTao = new DateTime(2024, 11, 15, 20, 18, 50, 355, DateTimeKind.Local).AddTicks(2177),
                            NguoiCapNhat = "Admin",
                            NguoiTao = "Admin",
                            TenThuongHieu = "Puma"
                        });
                });

            modelBuilder.Entity("AppData.Model.Voucher", b =>
                {
                    b.Property<Guid>("VoucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("GiaTriDonHangToiThieu")
                        .HasColumnType("int");

                    b.Property<int>("GiaTriGiam")
                        .HasColumnType("int");

                    b.Property<int>("LoaiGiamGia")
                        .HasColumnType("int");

                    b.Property<string>("MaVoucher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaVoucher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuongVoucherConLai")
                        .HasColumnType("int");

                    b.Property<int?>("SoTienToiDa")
                        .HasColumnType("int");

                    b.Property<int>("TongSoLuongVoucher")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("VoucherId");

                    b.ToTable("vouchers");
                });

            modelBuilder.Entity("AppData.Model.DiaChi", b =>
                {
                    b.HasOne("AppData.Model.KhachHang", "khachHang")
                        .WithMany("DiaChis")
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("khachHang");
                });

            modelBuilder.Entity("AppData.Model.GioHang", b =>
                {
                    b.HasOne("AppData.Model.KhachHang", "KhachHang")
                        .WithOne("GioHang")
                        .HasForeignKey("AppData.Model.GioHang", "IdKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("AppData.Model.GioHangChiTiet", b =>
                {
                    b.HasOne("AppData.Model.GioHang", "GioHang")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("IdGioHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("IdSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GioHang");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("AppData.Model.HinhAnh", b =>
                {
                    b.HasOne("AppData.Model.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("HinhAnhs")
                        .HasForeignKey("IdSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("AppData.Model.HoaDon", b =>
                {
                    b.HasOne("AppData.Model.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdKhachHang");

                    b.HasOne("AppData.Model.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdNhanVien");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("AppData.Model.HoaDonChiTiet", b =>
                {
                    b.HasOne("AppData.Model.HoaDon", "HoaDon")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("AppData.Model.LichSuHoaDon", b =>
                {
                    b.HasOne("AppData.Model.HoaDon", "HoaDon")
                        .WithMany("LichSuHoaDons")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.NhanVien", "NhanVien")
                        .WithMany("LichSuHoaDons")
                        .HasForeignKey("IdNhanVien")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HoaDon");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("AppData.Model.LichSuSuDungVoucher", b =>
                {
                    b.HasOne("AppData.Model.KhachHang", "KhachHang")
                        .WithMany("LichSuSuDungVouchers")
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppData.Model.Voucher", "Voucher")
                        .WithMany("LichSuSuDungVouchers")
                        .HasForeignKey("IdVoucher")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("AppData.Model.NhanVien", b =>
                {
                    b.HasOne("AppData.Model.ChucVu", "chucVu")
                        .WithMany("nhanViens")
                        .HasForeignKey("IdchucVu");

                    b.Navigation("chucVu");
                });

            modelBuilder.Entity("AppData.Model.PromotionSanPhamChiTiet", b =>
                {
                    b.HasOne("AppData.Model.Promotion", "Promotion")
                        .WithMany("PromotionSanPhamChiTiets")
                        .HasForeignKey("IdPromotion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("PromotionSanPhamChiTiets")
                        .HasForeignKey("IdSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promotion");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("AppData.Model.SanPham", b =>
                {
                    b.HasOne("AppData.Model.ChatLieu", "ChatLieu")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdChatLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.DanhMuc", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.DeGiay", "DeGiay")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdDeGiay")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.KieuDang", "KieuDang")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdKieuDang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.ThuongHieu", "ThuongHieu")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdThuongHieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatLieu");

                    b.Navigation("DanhMuc");

                    b.Navigation("DeGiay");

                    b.Navigation("KieuDang");

                    b.Navigation("ThuongHieu");
                });

            modelBuilder.Entity("AppData.Model.SanPhamChiTiet", b =>
                {
                    b.HasOne("AppData.Model.SanPham", "SanPham")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("AppData.Model.SanPhamChiTietKichCo", b =>
                {
                    b.HasOne("AppData.Model.KichCo", "KichCo")
                        .WithMany("SanPhamChiTietKichCos")
                        .HasForeignKey("IdKichCo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("SanPhamChiTietKichCos")
                        .HasForeignKey("IdSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KichCo");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("AppData.Model.SanPhamChiTietMauSac", b =>
                {
                    b.HasOne("AppData.Model.MauSac", "MauSac")
                        .WithMany("SanPhamChiTietMauSacs")
                        .HasForeignKey("IdMauSac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppData.Model.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("SanPhamChiTietMauSacs")
                        .HasForeignKey("IdSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MauSac");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("AppData.Model.ChatLieu", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("AppData.Model.ChucVu", b =>
                {
                    b.Navigation("nhanViens");
                });

            modelBuilder.Entity("AppData.Model.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("AppData.Model.DeGiay", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("AppData.Model.GioHang", b =>
                {
                    b.Navigation("GioHangChiTiets");
                });

            modelBuilder.Entity("AppData.Model.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiets");

                    b.Navigation("LichSuHoaDons");
                });

            modelBuilder.Entity("AppData.Model.KhachHang", b =>
                {
                    b.Navigation("DiaChis");

                    b.Navigation("GioHang");

                    b.Navigation("HoaDons");

                    b.Navigation("LichSuSuDungVouchers");
                });

            modelBuilder.Entity("AppData.Model.KichCo", b =>
                {
                    b.Navigation("SanPhamChiTietKichCos");
                });

            modelBuilder.Entity("AppData.Model.KieuDang", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("AppData.Model.MauSac", b =>
                {
                    b.Navigation("SanPhamChiTietMauSacs");
                });

            modelBuilder.Entity("AppData.Model.NhanVien", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("LichSuHoaDons");
                });

            modelBuilder.Entity("AppData.Model.Promotion", b =>
                {
                    b.Navigation("PromotionSanPhamChiTiets");
                });

            modelBuilder.Entity("AppData.Model.SanPham", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("AppData.Model.SanPhamChiTiet", b =>
                {
                    b.Navigation("GioHangChiTiets");

                    b.Navigation("HinhAnhs");

                    b.Navigation("HoaDonChiTiets");

                    b.Navigation("PromotionSanPhamChiTiets");

                    b.Navigation("SanPhamChiTietKichCos");

                    b.Navigation("SanPhamChiTietMauSacs");
                });

            modelBuilder.Entity("AppData.Model.ThuongHieu", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("AppData.Model.Voucher", b =>
                {
                    b.Navigation("LichSuSuDungVouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
